project:
  type: website
  output-dir: docs

website:
  title: "Academic Portfolio"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
        text: "Home"
        icon: house
      - href: about.qmd
        text: "About"
        icon: person
      - section: "Data Analysis I"
        contents:
          - text: "Homework 1: One Sample Inference"
            href: MATH354/1-HW-OneSampleInference/HW1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


execute:
  freeze: auto