{
  "hash": "c12eb259919e5d1ea49087c0e8986253",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 1: One-Sample Inference\"\nbody-classes: hw1-page\nauthor: \"Lions like to eat onions\"\nformat: html\n---\n\n## Question 1\n\n### Part a\n\nThe data are the proportions of successful retrievals out of 12 tests for each dog, so they are quantitative rather than simple 0/1 Bernoulli trials. Thus, a one-sample z-test is not a good fit.\n\nA one-sample t-test and Wilcoxon signed-rank test are plausible.\n\nFor the one-sample t-test, the population does not appear to be approximately Gaussian, since there are quite a few observations at the upper bound of 1 and the data are clearly left-skewed. The sample size ($n = 10$) is not large enough to rely on the CLT either. For the Wilcoxon signed-rank test, the data do not appear symmetric for the same reason stated above. The sample size is not large enough for the asymptotic approximation either. \n\nOne noticable thing is that quite a few observations have the same value, which introduces ties if the Wilcoxon test is applied. Furthermore, there are several zeros in the second data set (paired difference), which complicates the ranking process. Thus, I might choose to use the one-sample t-test.\n\n\n### Part b\n\n#### Research Question and Data\n\nStatistical Questions:\n\n1. Whether the dogs were better than chance, which we assume is 50%, at returning the new objects when requested.\n2. Whether there was a difference in the dogs' retrieval performance between the direct and overhearing conditions.\n\nResearchers observed \\(n = 10\\) dogs and recorded the proportion of\nsuccessful retrievals out of 12 tests for each dog. The observed\nproportions were\n\n$\\{1.0000,\\ 1.0000,\\ 0.7500,\\ 1.0000,\\ 0.4167,\\ 0.8333,\\ 0.7500,\\ 0.8333,\\ 0.8333,\\ 1.0000\\}$\n\n\nThey also considered the paired differences (direct − overhearing):\n\n$\\{-0.0833,\\ 0.0000,\\ -0.0833,\\ -0.0833,\\ 0.5833,\\ 0.0833,\\ -0.2500,\\ 0.1667,\\ 0.0000,\\ -0.4167\\}$\n\n\n#### Hypotheses\n\nWe want to test if the dogs were better than chance, so we use right sided test:\n\n$H_0: \\mu_X = 0.50$\n\n$H_a: \\mu_X > 0.50$\n\nwhere $\\mu_X$ is the population mean proportion of successful retrievals.\n\n\n#### Conditions for Use\n\n1. The variable of interest in quantitative.\n2. The sample is probably representative of the larger population.\n3. The sample observations are independent.\n4. The underlying population distribution is not approximately Gaussian, since the observed data arae left-skewed and have several observations at the upper bound of 1. In addition, the sample size ($n = 10$) is too small to use CLT.\n\n#### One-Sample t-Test\n\nThe one-sample t-test was performed using the following R code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(1.0000, 1.0000, 0.7500, 1.0000, 0.4167,\n       0.8333, 0.7500, 0.8333, 0.8333, 1.0000)\n\nt.test(x, mu = 0.50, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  x\nt = 5.9386, df = 9, p-value = 0.0001092\nalternative hypothesis: true mean is greater than 0.5\n95 percent confidence interval:\n 0.736198      Inf\nsample estimates:\nmean of x \n  0.84166 \n```\n\n\n:::\n:::\n\n\nThe test statistic is calculated as\n\n$$\nt = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}.\n$$\nThe sample mean was $\\bar{x} = 0.8417$. The test resulted in\n$t = 5.9386$ with $df = 9$ and a one-sided p-value of $0.0001092$.\n\n\n#### $p$-value\n\nWe use a right-tailed test ($\\mu_X > \\mu_0$).\n\n- Observations of t that are substantially larger than 0.5, which correspond to observations of $\\bar{x}$ that are substantially larger than $\\mu_0$.\n\n- $p\\text{-value} = P(T \\geq t) = P(T \\geq 5.9386) = 0.0001092$\n\n\n#### Results\n\nWe use the significance level $\\alpha = 0.05$. Since the $p\\text{-value} = 0.0001092$ is less than $0.05$, we reject the null hypothesis. The data provide statistically discernible support for the alternative hypothesis.\n\nThe test statistic $t = 5.9386$ indicates that the observed sample mean is approximately 5.94 standard errors above the null hypothesized mean of $0.50$. Therefore, the data suggest that the dogs' mean retrieval performance is better than chance.\n\n\n#### Effect Size\n\nTo evaluate the magnitude of the effect, Hedges'$g$ was calculated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effectsize)\n\ntest.result <- t.test(x, mu = 0.50, alternative = \"greater\")\n\nhedges_g(test.result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |      95% CI\n-----------------------\n1.72      | [0.88, Inf]\n\n- Deviation from a difference of 0.5.\n- One-sided CIs: upper bound fixed at [Inf].\n```\n\n\n:::\n:::\n\n\nThe estimated effect size was Hedges'$g = 1.72$, indicating a large effect. The mean retrieval performance was approximately 1.72 standard deviations above the chance level of $0.50$.\n\n\n#### Confidence Interval\n\nThe 95% confidence interval was obtained from the t-test result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest.result$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.736198      Inf\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nWe are 95% confident that the population mean retrieval proportion is approximately $[0.736, \\infty)$. Since this lower bound is above the chance level of $0.50$, the confidence interval is consistent with the conclusion that the dogs performed better than chance.\n\n\n## Question 2\n\n### Part a\n\nThe data a qualitative, and each trial is a Bournulli trial (either succeed or fail), so binomial distribution is possible. However, the trials may not be independent, since there should be correlations between each trials. Specifically, the performance of each dog in the two new-toy trials may tend to be consistent. Moreover, the probability of selecting the new toy by chance may not be exactly 50%, depending on dogs' behaviors.\n\n### Part b\n\nThe probability that a dog succeed in both trials are \n\n$$\np = (0.50)(0.50) = 0.25.\n$$\n\nLet $X_i = 1$ be the dog $i$ getting both toys right on the first try, and $X_i = 0$ be otherwise,\n\n$$\nX_i \\sim \\operatorname{Bornoulli}(0.25).\n$$\n\nTherefore, the total number of dogs getting both toys right follows a binomial distribution.\n\n$$\nB \\sim \\operatorname{Binomial}(10, 0.25).\n$$\n\nSince all 10 dogs got both trials right, \n\n$$\nP(B=10) = \\binom{10}{10}(0.25)^{10}(0.75)^0=(0.25)^{10} \\approx 9.54 \\times 10^{-7}.\n$$\n\nThus, the probability that all $n=10$ dogs would get both trials correct is approximately $9.54 \\times 10^{-7}$.\n\n\n### Part c\n\nThe Gaussian approximation has mean\n\n$$\n\\mu_Y = np = 10(0.25) = 2.5\n$$\n\nand standard deviation\n\n$$\n\\sigma_Y = \\sqrt{np(1-p)} = \\sqrt{10(0.25)(0.75)}\n\\approx 1.369.\n$$\n\nUsing the continuity correction,\n\n$$\nP(B=10)\n\\approx\nP(9.5 < Y < 10.5).\n$$\n\nAnd then we standardize it using\n\n$$\nZ = \\frac{Y-\\mu_Y}{\\sigma_Y}.\n$$\n\nThe lower and upper bounds are\n\n$$\n\\begin{aligned}\nz_{\\text{lower}} &= \\frac{9.5-2.5}{1.369}\n\\approx 5.11, \\\\\nz_{\\text{upper}} &= \\frac{10.5-2.5}{1.369}\n\\approx 5.84\n\\end{aligned}\n$$\n\nTherefore, \n\n$$\nP(B=10)\n\\approx\nP(5.11 < Z < 5.84)\n\\approx 1.57 \\times 10^{-7}.\n$$\n\nCompared to $9.54 \\times 10^{-7}$, which is the binomial probability from Part b, the Gaussian probability is much smaller. They are not close.\n\nThis is because one of the conditions to apply Gaussian distribution to approximate probabilities, is to make sure that\n\n$$\nnp \\ge 15,\\\\\nand \\\\\nn(1-p) \\ge 15.\n$$\n\nIn this case,\n\n$$\nnp = 10(0.25) = 2.5\\\\\nand \\\\\nn(1-p) = 10(1-0.25) = 7.5,\n$$\nboth of which are less than 15, so the Gaussian approximation conditions are not satisfied.",
    "supporting": [
      "HW1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}