{
  "hash": "93972c257a56439c7a6244f0a0e4a7e3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 2: k Sample Inference\"\nbody-classes: hw2-page\nauthor: \"Lions like to eat onions\"\nformat:\n  html:\n    number-sections: true\n    code-fold: true\n    code-line-numbers: true\n    cap-location: top\n\n  pdf:\n    documentclass: article\n    number-sections: true\n    reference-section-title: \"References\"\n    code-line-numbers: true\n    cap-location: top\n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n\nformat-links: [pdf]\n---\n\n## Question 1\n\n### Part a\n#### 1\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(354)\n\nR <- 1000\nsimulations <- vector(\"list\", R)\n\nfor (i in 1:R) {\n  simulations[[i]] <- data.frame(\n    value = rnorm(150, mean = 0, sd = 1),\n    group = factor(rep(1:5, each = 30))\n  )\n}\n```\n:::\n\n\n#### 2\n\n::: {.cell}\n\n```{.r .cell-code}\nerror_unadjusted <- logical(R)\n\nfor (i in 1:R) {\n  dat <- simulations[[i]]\n\n  test_unadjusted <- pairwise.t.test(\n    dat$value, dat$group,\n    p.adjust.method = \"none\"\n  )\n\n  error_unadjusted[i] <- any(\n    test_unadjusted$p.value < 0.05,\n    na.rm = TRUE\n  )\n}\n\nmean(error_unadjusted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.294\n```\n\n\n:::\n:::\n\n\nAt least one pairwise comparison provided statistically discernible\nsupport for a non-zero mean difference in\n294 of the 1,000 simulations (p < 0.05).\nThese are Type I errors,\ngiving an estimated family-wise error rate of\n29.4%.\n\n#### 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerror_tukey <- logical(R)\n\nfor (i in 1:R) {\n  dat <- simulations[[i]]\n\n  fit <- aov(value ~ group, data = dat)\n  test_tukey <- rstatix::tukey_hsd(fit)\n\n  error_tukey[i] <- any(test_tukey$p.adj < 0.05)\n}\n\nmean(error_tukey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.053\n```\n\n\n:::\n:::\n\n\nAfter Tukey's HSD adjustment, at least one pairwise comparison\nprovided statistically discernible support for a non-zero mean\ndifference in 53 of the 1,000 simulations\n(adjusted p < 0.05).\nSince all population means were zero, these are Type I errors,\nand the estimated family-wise error rate is\n5.3%.\n\n\n### Part b\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerror_bh <- logical(R)\n\nfor (i in 1:R) {\n  dat <- simulations[[i]]\n\n  test_bh <- pairwise.t.test(\n    dat$value, dat$group,\n    p.adjust.method = \"BH\"\n  )\n\n  error_bh[i] <- any(\n    test_bh$p.value < 0.05,\n    na.rm = TRUE\n  )\n}\n\nmean(error_bh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.047\n```\n\n\n:::\n:::\n\n\nAfter BH adjustment, at least one pairwise comparison provided\nstatistically discernible support for a non-zero mean difference\nin 47 of the 1,000 simulations, giving an estimated\nfamily-wise error rate of 4.7%.\nThis was much lower than the unadjusted rate of\n29.4% and close to Tukey's\nrate of 5.3%.\n\nBH targets the false discovery rate (FDR), whereas Tukey's HSD\ncontrols the family-wise error rate (FWER). \n\n## Question 2\n\n### Part a\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Required sample size per group\npwr::pwr.anova.test(\n  k = 5,\n  f = 0.25,\n  sig.level = 0.05,\n  power = 0.80\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Balanced one-way analysis of variance power calculation \n\n              k = 5\n              n = 39.1534\n              f = 0.25\n      sig.level = 0.05\n          power = 0.8\n\nNOTE: n is number in each group\n```\n\n\n:::\n\n```{.r .cell-code}\n# Power curve\nn <- 2:100\n\npower <- sapply(n, function(x) {\n  pwr::pwr.anova.test(\n    k = 5, n = x, f = 0.25, sig.level = 0.05\n  )$power\n})\n\nplot(n, power, type = \"l\",\n     xlab = \"Sample size per group\",\n     ylab = \"Power\",\n     main = \"ANOVA Power Curve\")\n\nabline(h = 0.80, col = \"red\", lty = 2)\nabline(v = 40, col = \"blue\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe required sample size is roughly 40 participants per group and 200 in total.\nThe graph shows that 40 participants per group achieves slightly\nmore than 80% power.\n\nSince every group in the original groups had more than 40\nparticipants, the study is powered for the overall\nANOVA under the assumed moderate effect size. This calculation\nassumes equal group sizes, so it does not provide the exact power\nof the original unequal-sized design.\n\n\n### Part b\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Non-centrality parameter and power\nlambda <- 150 * 0.25^2\nlambda\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.375\n```\n\n\n:::\n\n```{.r .cell-code}\ncritical <- qf(0.95, 4, 145)\npf(critical, 4, 145, ncp = lambda, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6675964\n```\n\n\n:::\n\n```{.r .cell-code}\n# Alternative F distribution\ncurve(df(x, 4, 145, ncp = lambda), from = 0, to = 10,\n      xlab = \"F\", ylab = \"Density\",\n      main = \"Alternative F Distribution: N = 150\")\nabline(v = critical, col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nWith 30 participants per group, the non-centrality parameter is\n9.375 and the power is approximately 66.8%. Therefore, N = 150\nis insufficient to achieve the desired 80% power.\n\n### Part c\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Power for different sample sizes per group\nn <- 40:500\n\npower_c <- sapply(n, function(x) {\n  PMCMRplus::power.tukey.test(\n    n = x,\n    groups = 5,\n    delta = 0.25,\n    within.var = 0.7152,\n    sig.level = 0.05\n  )$power\n})\n\n# Power with 40 participants per group\npower_c[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07866837\n```\n\n\n:::\n\n```{.r .cell-code}\n# Smallest sample size achieving at least 80% power\nn_required <- min(n[power_c >= 0.80])\nn_required\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 293\n```\n\n\n:::\n:::\n\n\nAn overall ANOVA can detect differences among groups having different\nmeans. However, detecting the smaller difference between\nstages 1 and 2 is harder, especially after Tukey's adjustment\nfor multiple comparisons.\n\nWith 40 participants per group, the power is only about 7.9%.\nUsing the pooled variance of 0.7152, approximately 293 participants\nper group are needed to achieve 80% power for this comparison.\n\n### Part d\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Superpower)\n\nfor (n in c(40, 80)) {\n\n  design <- ANOVA_design(\n    design = \"5b\",\n    n = n,\n    mu = c(2.92, 3.11, 3.36, 4.04, 4.35),\n    sd = sqrt(0.80),\n    plot = FALSE\n  )\n\n  result <- ANOVA_power(\n    design,\n    nsims = 1000,\n    seed = 354,\n    emm = TRUE,\n    emm_p_adjust = \"tukey\",\n    verbose = FALSE\n  )\n\n  print(paste(\"Sample size per group:\", n))\n  print(result$main_result)\n  print(result$emm_results)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Sample size per group: 40\"\n        power effect_size\nanova_a   100   0.2875741\n        contrast power    cohen_f\np_1  a_a1 - a_a2   3.2 0.07851998\np_2  a_a1 - a_a3  29.8 0.16043752\np_3  a_a1 - a_a4  99.7 0.40079656\np_4  a_a1 - a_a5 100.0 0.51421433\np_5  a_a2 - a_a3   6.4 0.09965935\np_6  a_a2 - a_a4  96.8 0.33441403\np_7  a_a2 - a_a5  99.9 0.44783180\np_8  a_a3 - a_a4  73.3 0.24120424\np_9  a_a3 - a_a5  98.1 0.35462200\np_10 a_a4 - a_a5  11.9 0.11742044\n[1] \"Sample size per group: 80\"\n        power effect_size\nanova_a   100   0.2797892\n        contrast power    cohen_f\np_1  a_a1 - a_a2   8.2 0.07492609\np_2  a_a1 - a_a3  67.3 0.15861698\np_3  a_a1 - a_a4 100.0 0.39912272\np_4  a_a1 - a_a5 100.0 0.51008441\np_5  a_a2 - a_a3  18.1 0.09050315\np_6  a_a2 - a_a4 100.0 0.32897230\np_7  a_a2 - a_a5 100.0 0.43993399\np_8  a_a3 - a_a4  98.4 0.24067913\np_9  a_a3 - a_a5 100.0 0.35164081\np_10 a_a4 - a_a5  30.1 0.11153257\n```\n\n\n:::\n:::\n\n\nDoubling the sample size from 40 to 80 per group increases power,\nbut is still insufficient to achieve 80% power for every pairwise\ncomparison. In specific, the small difference between stages\n0 and 1 (3.11 − 2.92 = 0.19) remains difficult to detect.\n\n\n## Question 3\n\n### Part a\n\nLet $\\mu_{2C}$, $\\mu_{6C}$, $\\mu_{16C}$, and $\\mu_{16T}$ denote\nthe population mean SUVmax values for the 2-month control,\n6-month control, 16-month control, and 16-month treatment groups,\nrespectively.\n\n$$\nH_0: \\mu_{2C} = \\mu_{6C} = \\mu_{16C} = \\mu_{16T}\n$$\n\n$$\nH_a: \\text{At least one population mean differs.}\n$$\n\n### Part b\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat3 <- data.frame(\n  SUVmax = c(\n    1.48969, 1.30168, 1.30620,\n    4.36000, 4.28807, 3.64184,\n    7.30182, 7.12416, 8.28764,\n    4.69304, 2.51326, 2.38019\n  ),\n  group = factor(\n    rep(c(\"2M Control\", \"6M Control\",\n          \"16M Control\", \"16M Treatment\"), each = 3),\n    levels = c(\"2M Control\", \"6M Control\",\n               \"16M Control\", \"16M Treatment\")\n  )\n)\n\n# Means and standard deviations\naggregate(SUVmax ~ group, data = dat3, FUN = mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          group   SUVmax\n1    2M Control 1.365857\n2    6M Control 4.096637\n3   16M Control 7.571207\n4 16M Treatment 3.195497\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(SUVmax ~ group, data = dat3, FUN = sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          group    SUVmax\n1    2M Control 0.1072666\n2    6M Control 0.3955041\n3   16M Control 0.6267761\n4 16M Treatment 1.2986162\n```\n\n\n:::\n\n```{.r .cell-code}\n# Display all observations\nstripchart(SUVmax ~ group, data = dat3,\n           vertical = TRUE, method = \"stack\", pch = 19,\n           xlab = \"Group\", ylab = \"Heart SUVmax\",\n           main = \"Heart SUVmax by Age and Treatment\",\n           cex.axis = 0.8)\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nAmong the control groups, mean heart SUVmax increased with age\n(approximately 1.37, 4.10, and 7.57 for 2, 6, and 16 months,\nrespectively). The 16-month treatment group had a lower mean\n(approximately 3.20) than the 16-month control group, placing it\nbetween the two younger control groups.\n\n### Part c\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest3 <- oneway.test(SUVmax ~ group, data = dat3)\ntest3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  SUVmax and group\nF = 98.464, num df = 3.0000, denom df = 3.5496, p-value = 0.0006851\n```\n\n\n:::\n:::\n\n\nSUVmax is quantitative. The sample standard deviations differ\nsubstantially across groups, so I used Welch's ANOVA because it does\nnot assume equal population variances. The rats are not connected in certain ways so I assume independence. The observations per group are three, which is low, so the results should be interpreted cautiously.\n\nWelch's ANOVA gives\n$F = 98.46$,\nwith 3 and\n3.55 degrees of freedom\n(p = 6.85\\times 10^{-4}).\nSince p < 0.05, we reject the null hypothesis. The data provide\nstatistically discernible support that at least one population\nmean heart SUVmax differs among the four groups.\n\n### Part d\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposthoc3 <- rstatix::games_howell_test(\n  dat3, SUVmax ~ group\n)\n\nposthoc3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  .y.    group1      group2     estimate conf.low conf.high   p.adj p.adj.signif\n* <chr>  <chr>       <chr>         <dbl>    <dbl>     <dbl>   <dbl> <chr>       \n1 SUVmax 2M Control  6M Control    2.73      1.31     4.15  0.0119  *           \n2 SUVmax 2M Control  16M Contr…    6.21      3.81     8.60  0.00720 **          \n3 SUVmax 2M Control  16M Treat…    1.83     -3.30     6.96  0.308   ns          \n4 SUVmax 6M Control  16M Contr…    3.47      1.56     5.39  0.00801 **          \n5 SUVmax 6M Control  16M Treat…   -0.901    -5.47     3.67  0.698   ns          \n6 SUVmax 16M Control 16M Treat…   -4.38     -8.51    -0.244 0.0431  *           \n```\n\n\n:::\n:::\n\n\nGames–Howell comparisons showed statistically discernible increases in mean heart SUVmax across the control groups: 2 versus 6 months (adjusted p = 0.0119), 2 versus 16 months (p = 0.0072), and 6 versus 16 months (p = 0.00801). The 16-month treatment group had a lower mean than the 16-month control group (estimated difference = −4.38, adjusted p = 0.0431), supporting a reduction associated with low-dose nicotine.\n\nThe treatment group did not differ significantly from the 2-month or 6-month control groups (adjusted p = 0.308 and 0.698, respectively), but these results do not establish equivalence to younger mice.\n\n### Part e\n\nThe results support the hypothesis that SUVmax increases with age and is reduced by low-dose nicotine in older mice. All three control groups differed significantly, with higher mean SUVmax at older ages. Although the treatment group did not differ significantly from the younger controls, this does not establish that treatment restored SUVmax to younger levels. ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}